// This file is generated by npm run build:icons

export type IconName =
  | "arrow--right"
  | "attachment"
  | "codepen"
  | "github"
  | "linkedin"
  | "medium"
  | "tiktok"
  | "twitch"
  | "twitter"
  | "youtube";
